spring.application.name=guias-despacho

# Configuración de la base de datos H2
spring.datasource.url=jdbc:h2:mem:guiasdb;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

aws.region=${AWS_REGION}
aws.s3.bucket=${AWS_BUCKET}
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/af624e15-c645-4a4f-b9dc-41a1b12a9ed1/v2.0